package parser

import "log/slog"

// tmplFunc is the signature for all analyzer template functions.
// Functions receive a context and Call (with unevaluated args), then return evalResult.
type tmplFunc func(ctx *evalCtx, call Call) evalResult

// funcMap holds real analyzer handlers used during evaluation.
var funcMap map[string]tmplFunc

// stubFuncMap lists all known function names for the parser (stubs only).
var stubFuncMap map[string]interface{}

// stub parser function for the stubFuncMap
var parseStub = func(...interface{}) interface{} { return nil }

func init() {
	// 1) Build evaluation registry with concrete handlers or not-implemented stubs.
	funcMap = map[string]tmplFunc{
		// Analysis-aware real handlers
		"include": includeFn,
		"tpl":     tplFn,
		"default": defaultFn,
		"dict":    dictFn,
		"get":     getFn,
		"index":   indexFn,

		// Pass-through helpers (preserve .Values usage)
		"indent":   emitArgsNoResultFn,
		"lower":    unaryPassThroughFn,
		"nindent":  emitArgsNoResultFn,
		"quote":    unaryPassThroughFn,
		"required": emitArgsNoResultFn,
		"upper":    unaryPassThroughFn,

		// Serializers (treated as unary pass-through for analysis)
		"toYaml":       unaryPassThroughFn,
		"mustToYaml":   unaryPassThroughFn,
		"toYamlPretty": unaryPassThroughFn,
		"toJson":       unaryPassThroughFn,
		"mustToJson":   unaryPassThroughFn,
		"toToml":       unaryPassThroughFn,

		// Data conversion: ignored in analysis
		"fromJson":         noopStrings,
		"fromJsonArray":    noopStrings,
		"fromYaml":         noopStrings,
		"fromYamlArray":    noopStrings,
		"fromToml":         noopStrings,
		"mustFromJson":     noopStrings,
		"mustToPrettyJson": noopStrings,
		"mustToRawJson":    noopStrings,
		"toPrettyJson":     unaryPassThroughFn,
		"toRawJson":        unaryPassThroughFn,

		// Common collection/string helpers
		"abbrev":                     unaryPassThroughFn,
		"abbrevboth":                 unaryPassThroughFn,
		"add":                        emitArgsNoResultFn,
		"add1":                       emitArgsNoResultFn,
		"add1f":                      emitArgsNoResultFn,
		"addf":                       emitArgsNoResultFn,
		"adler32sum":                 noopStrings,
		"ago":                        noopStrings,
		"all":                        emitArgsNoResultFn,
		"and":                        emitArgsNoResultFn,
		"any":                        emitArgsNoResultFn,
		"append":                     emitArgsNoResultFn,
		"atoi":                       emitArgsNoResultFn,
		"b32dec":                     unaryPassThroughFn,
		"b32enc":                     unaryPassThroughFn,
		"b64dec":                     unaryPassThroughFn,
		"b64enc":                     unaryPassThroughFn,
		"base":                       unaryPassThroughFn,
		"bcrypt":                     emitArgsNoResultFn,
		"biggest":                    emitArgsNoResultFn,
		"buildCustomCert":            noopStrings,
		"call":                       emitArgsNoResultFn,
		"camelcase":                  unaryPassThroughFn,
		"cat":                        emitArgsNoResultFn,
		"ceil":                       emitArgsNoResultFn,
		"chunk":                      unaryPassThroughFn,
		"clean":                      unaryPassThroughFn,
		"coalesce":                   emitArgsNoResultFn,
		"compact":                    unaryPassThroughFn,
		"concat":                     emitArgsNoResultFn,
		"contains":                   binaryEvalFn,
		"date":                       noopStrings,
		"dateInZone":                 noopStrings,
		"dateModify":                 noopStrings,
		"date_in_zone":               noopStrings,
		"date_modify":                noopStrings,
		"decryptAES":                 emitArgsNoResultFn,
		"deepCopy":                   unaryPassThroughFn,
		"deepEqual":                  binaryEvalFn,
		"derivePassword":             emitArgsNoResultFn,
		"dig":                        emitArgsNoResultFn,
		"dir":                        unaryPassThroughFn,
		"div":                        emitArgsNoResultFn,
		"divf":                       emitArgsNoResultFn,
		"duration":                   noopStrings,
		"durationRound":              noopStrings,
		"empty":                      emitArgsNoResultFn,
		"encryptAES":                 emitArgsNoResultFn,
		"eq":                         binaryEvalFn,
		"ext":                        unaryPassThroughFn,
		"first":                      unaryPassThroughFn,
		"float64":                    emitArgsNoResultFn,
		"floor":                      emitArgsNoResultFn,
		"ge":                         binaryEvalFn,
		"genCA":                      noopStrings,
		"genCAWithKey":               noopStrings,
		"genPrivateKey":              noopStrings,
		"genSelfSignedCert":          noopStrings,
		"genSelfSignedCertWithKey":   noopStrings,
		"genSignedCert":              noopStrings,
		"genSignedCertWithKey":       noopStrings,
		"gt":                         binaryEvalFn,
		"has":                        binaryEvalFn,
		"hasKey":                     binaryEvalFn,
		"hasPrefix":                  binaryEvalFn,
		"hasSuffix":                  binaryEvalFn,
		"hello":                      noopStrings,
		"html":                       unaryPassThroughFn,
		"htmlDate":                   noopStrings,
		"htmlDateInZone":             noopStrings,
		"htpasswd":                   emitArgsNoResultFn,
		"initial":                    unaryPassThroughFn,
		"initials":                   unaryPassThroughFn,
		"int":                        emitArgsNoResultFn,
		"int64":                      emitArgsNoResultFn,
		"isAbs":                      emitArgsNoResultFn,
		"join":                       emitArgsNoResultFn,
		"js":                         unaryPassThroughFn,
		"kebabcase":                  unaryPassThroughFn,
		"keys":                       unaryPassThroughFn,
		"kindIs":                     binaryEvalFn,
		"kindOf":                     unaryPassThroughFn,
		"last":                       unaryPassThroughFn,
		"le":                         binaryEvalFn,
		"len":                        emitArgsNoResultFn,
		"list":                       emitArgsNoResultFn,
		"lt":                         binaryEvalFn,
		"max":                        emitArgsNoResultFn,
		"maxf":                       emitArgsNoResultFn,
		"merge":                      emitArgsNoResultFn,
		"mergeOverwrite":             emitArgsNoResultFn,
		"min":                        emitArgsNoResultFn,
		"minf":                       emitArgsNoResultFn,
		"mod":                        emitArgsNoResultFn,
		"mul":                        emitArgsNoResultFn,
		"mulf":                       emitArgsNoResultFn,
		"mustAppend":                 emitArgsNoResultFn,
		"mustChunk":                  unaryPassThroughFn,
		"mustCompact":                unaryPassThroughFn,
		"mustDateModify":             noopStrings,
		"mustDeepCopy":               unaryPassThroughFn,
		"mustFirst":                  unaryPassThroughFn,
		"mustHas":                    binaryEvalFn,
		"mustInitial":                unaryPassThroughFn,
		"mustLast":                   unaryPassThroughFn,
		"mustMerge":                  emitArgsNoResultFn,
		"mustMergeOverwrite":         emitArgsNoResultFn,
		"mustPrepend":                emitArgsNoResultFn,
		"mustPush":                   emitArgsNoResultFn,
		"mustRegexFind":              binaryEvalFn,
		"mustRegexFindAll":           emitArgsNoResultFn,
		"mustRegexMatch":             binaryEvalFn,
		"mustRegexReplaceAll":        emitArgsNoResultFn,
		"mustRegexReplaceAllLiteral": emitArgsNoResultFn,
		"mustRegexSplit":             emitArgsNoResultFn,
		"mustReverse":                unaryPassThroughFn,
		"mustRest":                   unaryPassThroughFn,
		"mustSlice":                  unaryPassThroughFn,
		"mustToDate":                 noopStrings,
		"mustUniq":                   unaryPassThroughFn,
		"mustWithout":                emitArgsNoResultFn,
		"must_date_modify":           noopStrings,
		"ne":                         binaryEvalFn,
		"nospace":                    unaryPassThroughFn,
		"not":                        emitArgsNoResultFn,
		"now":                        noopStrings,
		"omit":                       emitArgsNoResultFn,
		"or":                         emitArgsNoResultFn,
		"osBase":                     unaryPassThroughFn,
		"osClean":                    unaryPassThroughFn,
		"osDir":                      unaryPassThroughFn,
		"osExt":                      unaryPassThroughFn,
		"osIsAbs":                    emitArgsNoResultFn,
		"pick":                       emitArgsNoResultFn,
		"pluck":                      emitArgsNoResultFn,
		"plural":                     emitArgsNoResultFn,
		"prepend":                    emitArgsNoResultFn,
		"print":                      emitArgsNoResultFn,
		"printf":                     emitArgsNoResultFn,
		"println":                    emitArgsNoResultFn,
		"push":                       emitArgsNoResultFn,
		"randAlpha":                  noopStrings,
		"randAlphaNum":               noopStrings,
		"randAscii":                  noopStrings,
		"randBytes":                  noopStrings,
		"randInt":                    noopStrings,
		"randNumeric":                noopStrings,
		"regexFind":                  binaryEvalFn,
		"regexFindAll":               emitArgsNoResultFn,
		"regexMatch":                 binaryEvalFn,
		"regexQuoteMeta":             unaryPassThroughFn,
		"regexReplaceAll":            emitArgsNoResultFn,
		"regexReplaceAllLiteral":     emitArgsNoResultFn,
		"regexSplit":                 emitArgsNoResultFn,
		"repeat":                     emitArgsNoResultFn,
		"replace":                    emitArgsNoResultFn,
		"rest":                       unaryPassThroughFn,
		"reverse":                    unaryPassThroughFn,
		"round":                      emitArgsNoResultFn,
		"semver":                     emitArgsNoResultFn,
		"semverCompare":              binaryEvalFn,
		"seq":                        noopStrings,
		"set":                        emitArgsNoResultFn,
		"sha1sum":                    emitArgsNoResultFn,
		"sha256sum":                  emitArgsNoResultFn,
		"sha512sum":                  emitArgsNoResultFn,
		"shuffle":                    unaryPassThroughFn,
		"slice":                      emitArgsNoResultFn,
		"snakecase":                  unaryPassThroughFn,
		"sortAlpha":                  unaryPassThroughFn,
		"split":                      emitArgsNoResultFn,
		"splitList":                  emitArgsNoResultFn,
		"splitn":                     emitArgsNoResultFn,
		"squote":                     unaryPassThroughFn,
		"sub":                        emitArgsNoResultFn,
		"subf":                       emitArgsNoResultFn,
		"substr":                     emitArgsNoResultFn,
		"swapcase":                   unaryPassThroughFn,
		"ternary":                    emitArgsNoResultFn,
		"title":                      unaryPassThroughFn,
		"toDate":                     noopStrings,
		"toDecimal":                  unaryPassThroughFn,
		"toString":                   unaryPassThroughFn,
		"toStrings":                  unaryPassThroughFn,
		"trim":                       unaryPassThroughFn,
		"trimAll":                    emitArgsNoResultFn,
		"trimPrefix":                 binaryEvalFn,
		"trimSuffix":                 binaryEvalFn,
		"trimall":                    emitArgsNoResultFn,
		"trunc":                      noopStrings,
		"tuple":                      emitArgsNoResultFn,
		"typeIs":                     binaryEvalFn,
		"typeIsLike":                 binaryEvalFn,
		"typeOf":                     unaryPassThroughFn,
		"uniq":                       unaryPassThroughFn,
		"unixEpoch":                  noopStrings,
		"unset":                      emitArgsNoResultFn,
		"until":                      noopStrings,
		"untilStep":                  noopStrings,
		"untitle":                    unaryPassThroughFn,
		"urlJoin":                    emitArgsNoResultFn,
		"urlParse":                   emitArgsNoResultFn,
		"urlquery":                   unaryPassThroughFn,
		"uuidv4":                     noopStrings,
		"values":                     unaryPassThroughFn,
		"without":                    emitArgsNoResultFn,
		"wrap":                       emitArgsNoResultFn,
		"wrapWith":                   emitArgsNoResultFn,

		// Not implemented (surface usage in Strict tests)
		"fail":          emitArgsNoResultFn,
		"lookup":        noopStrings,
		"getHostByName": noopStrings,
	}

	// 2) Build parse stubs from eval keys
	stubFuncMap = make(map[string]interface{}, len(funcMap))
	for name := range funcMap {
		stubFuncMap[name] = parseStub
	}
}

func getTemplateFunction(name string) tmplFunc {
	if fn, ok := funcMap[name]; ok {
		return fn
	}
	slog.Warn("unknown template function name", "name", name)
	return makeNotImplementedFn(name)
}
