version: 2

builds:
  - id: helm-snoop
    main: ./cmd/helm-snoop
    binary: helm-snoop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/y0-l0/helm-snoop/pkg/version.version={{.Version}}
      - -X github.com/y0-l0/helm-snoop/pkg/version.commit={{.Commit}}
      - -X github.com/y0-l0/helm-snoop/pkg/version.treeState={{if .IsGitDirty}}dirty{{else}}clean{{end}}
      - -X github.com/y0-l0/helm-snoop/pkg/version.commitDate={{.CommitDate}}

nfpms:
  - id: linux-packages
    package_name: helm-snoop
    ids:
      - helm-snoop
    vendor: stadimeter
    homepage: https://github.com/y0-l0/helm-snoop
    maintainer: "y0-l0 <jojo.dev@lohmer.com>"
    description: Detect unused and undefined values in Helm charts
    license: AGPL-3.0
    formats:
      - deb
    bindir: /usr/bin

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

dockers_v2:
  - images:
      - ghcr.io/y0-l0/helm-snoop
    dockerfile: Dockerfile.distroless
    tags:
      - "{{ .Version }}"
      - latest
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .ShortCommit }}"
      org.opencontainers.image.created: "{{ .Date }}"

homebrew_casks:
  - repository:
      owner: y0-l0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/y0-l0/helm-snoop
    description: Detect unused and undefined values in Helm charts
    license: AGPL-3.0

publishers:
  - name: fury
    ids:
      - linux-packages
    checksum: false
    signature: false
    dir: "{{ dir .ArtifactPath }}"
    cmd: >-
      curl --silent --show-error --fail
      -F package=@{{ .ArtifactName }}
      https://{{ .Env.FURY_TOKEN }}@push.fury.io/{{ .Env.FURY_ACCOUNT }}/

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
