version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/helm-snoop
    binary: helm-snoop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/y0-l0/helm-snoop/pkg/version.version={{.Version}}
      - -X github.com/y0-l0/helm-snoop/pkg/version.commit={{.Commit}}
      - -X github.com/y0-l0/helm-snoop/pkg/version.treeState={{if .IsGitDirty}}dirty{{else}}clean{{end}}
      - -X github.com/y0-l0/helm-snoop/pkg/version.commitDate={{.CommitDate}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

dockers:
  - id: helm-snoop-amd64
    dockerfile: Dockerfile.distroless
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/y0-l0/helm-snoop:{{ .Version }}-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .ShortCommit }}
      - --label=org.opencontainers.image.created={{ .Date }}

  - id: helm-snoop-arm64
    dockerfile: Dockerfile.distroless
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/y0-l0/helm-snoop:{{ .Version }}-arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .ShortCommit }}
      - --label=org.opencontainers.image.created={{ .Date }}

docker_manifests:
  - name_template: ghcr.io/y0-l0/helm-snoop:{{ .Version }}
    image_templates:
      - ghcr.io/y0-l0/helm-snoop:{{ .Version }}-amd64
      - ghcr.io/y0-l0/helm-snoop:{{ .Version }}-arm64

  - name_template: ghcr.io/y0-l0/helm-snoop:latest
    image_templates:
      - ghcr.io/y0-l0/helm-snoop:{{ .Version }}-amd64
      - ghcr.io/y0-l0/helm-snoop:{{ .Version }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
