- id: helm-snoop
  name: helm-snoop
  description: Detect unused and undefined values in Helm charts (requires helm-snoop on PATH)
  entry: helm-snoop
  language: system
  files: (Chart\.yaml|values\.yaml|values/.*\.yaml|templates/.*)$
  pass_filenames: true
  require_serial: true

- id: helm-snoop-docker
  name: helm-snoop (docker)
  description: Detect unused and undefined values in Helm charts (via Docker)
  entry: ghcr.io/y0-l0/helm-snoop:latest
  language: docker_image
  files: (Chart\.yaml|values\.yaml|values/.*\.yaml|templates/.*)$
  pass_filenames: true
  require_serial: true
