sonar.projectKey=Y0-L0_helm-snoop
sonar.organization=y0-l0

sonar.sources=.
sonar.exclusions=**/*_test.go,testdata/**,cmd/golden/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
